### ISSUE TITLE
Feature: User can see upcoming holidays on their calendar.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see upcoming holidays on their calendar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the calendar, holidays will appear in pink, and will display the holiday name next to the date.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/121247868-960bd580-c857-11eb-970a-c5f6bf688f24.png)
![image](https://user-images.githubusercontent.com/59109937/121249923-fef44d00-c859-11eb-95da-f78f23f0c0c5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create HTML and CSS to layout the calendar.
- [x] Create data model for the calendar, containing home and dates containing weather, holidays, travel, birthdays, meetings, hangouts, and events.
- [x] Load in numbers for each day of the month, starting on the current day.
- [x] Highlight the current day.
- [x] Allow days to be selected, and display the selected day's info.
- [x] Write AJAX code to retrieve holiday information.
- [x] Input the holiday information into the calendar and display it.
- [x] Adjust CSS for desktop view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
