### ISSUE TITLE
Refactor: Refactor to ES6

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/ajax-project#15]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] update data.js
- [x] update constructors.js
- [x] replace var with const and let in main.js
- [x] condense code using arrow functions and for of loops
- [x] bug fixes
