### ISSUE TITLE
Feature: User can see each day's weather.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see each day's weather.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can see the weather on the calendar in desktop view, and will get more detailed information when selecting the day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/121442453-946a0c80-c940-11eb-9a12-5e603ae251d1.png)
![image](https://user-images.githubusercontent.com/59109937/121442490-a21f9200-c940-11eb-8ea2-7bd081dd1432.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Import all SVGs.
- [x] Write AJAX code for retrieving weather data.
- [x] Display weather data when the day is selected.
- [x] Fill in the weather data in desktop view.
