### ISSUE TITLE
Feature: User can record their travel days.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can record their travel days.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user will specify a hometown that will be used to find the weather.  The user can add a travel destination as well, which will show up in a different color on the calendar, and display different weather.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/121586662-c33bbd80-c9e8-11eb-9fd3-46712d30c4d1.png)
![image](https://user-images.githubusercontent.com/59109937/121586715-d058ac80-c9e8-11eb-99af-0564aaa2ecde.png)
![image](https://user-images.githubusercontent.com/59109937/121586749-da7aab00-c9e8-11eb-9c04-28176fccf204.png)
![image](https://user-images.githubusercontent.com/59109937/121586783-eb2b2100-c9e8-11eb-807a-424ecc5bb692.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create modal for requesting a hometown.
- [x] Input the hometown into the data model, and hide the modal when there is a hometown.
- [x] Create an HTTP request for getting the lat and lon using a name for the location.
- [x] Update the weather HTTP request to use a specific lat and lon.
- [x] Make CSS for displaying a new travel location.
- [x] Create add event and add travel buttons.
- [x] Modify the modal to request a travel destination.
- [x] Save the travel destination and update the calendar accordingly.
- [x] Update the travel days with the new weather.
- [x] Adjust modal for desktop.
