### ISSUE TITLE
Feature: User can add events to the calendar.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add events to the calendar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a day is selected, the user can add an event (event, birthday, hangout, meeting) that will appear in a to-do list for that day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/121788443-2e6cc780-cb82-11eb-9629-e63fa1d27e02.png)
![image](https://user-images.githubusercontent.com/59109937/121788447-36c50280-cb82-11eb-9b1e-3cd10566bfe4.png)
![image](https://user-images.githubusercontent.com/59109937/121788452-43e1f180-cb82-11eb-9171-ad0244aee37e.png)
![image](https://user-images.githubusercontent.com/59109937/121788458-4c3a2c80-cb82-11eb-89b6-ee933d2abdfb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create modal for adding events.
- [x] Make event listener to open the modal.
- [x] Make event listeners for the Cancel, Save, and Save+ options on the modal.
- [x] Assign the event data to `data.days`.
- [x] Populate the checklist with the event data.
- [x] Order events in the checklist by birthday > meeting > hangout > event // no time > earlier > later.
- [x] Add an edit button for each event.
- [x] Update the code to enable edits to events.
- [x] Add a delete button to the event modal.
- [x] Update the code to enable event deletion.
- [x] Update the desktop view to display the first 3 events of a day.
