### ISSUE TITLE
Feature: User can check off their events.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can check off their events.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user presses the radio button next to an event, it will appear checked, and stay that way if the user leaves the day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/122264311-4303d500-ce8c-11eb-845d-db07c31e2261.png)
![image](https://user-images.githubusercontent.com/59109937/122264362-4f882d80-ce8c-11eb-880d-c177865bc2d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the checklist handler to check for pressing the radio button.
- [x] Change the state of the CalendarEvent object when the radio button is pressed.
- [x] Update the checklist loader to account for whether or not an event is checked.
- [x] Bug fixes.
